### ISSUE TITLE
Delete a storage node would cause data loss.

### ISSUE THREAD

**Issue by NewDund** [leo-project/leofs#1115] opened 2018-08-31 05:45 UTC
There is a very serious problem here.

When I dropped a storage node, I found that some objects would disappear. My copy number is three.Is there any setup to ensure data integrity?

So, I want to know how Leofs's replica storage strategy is. And how to solve this problem.

I hope to answer this question as soon as possible.

**Comment by mocchira** [comment] 2018-08-31 07:44
> When I dropped a storage node, I found that some objects would disappear. My copy number is three.Is there any setup to ensure data integrity?

Let me clarify what the drop operation was in detail.
Did you do the proper detach step described on the official doc: https://leo-project.net/leofs/docs/admin/system_operations/cluster/#remove-a-node OR
just stop and delete the node?

- The former
  - There should be no chances to lose any objects as long as all storage nodes are healthy and rebalance get finished without any errors.
- The latter
  - Even though your copy number is three, there are some cases that data lost could happen in case your consistency setting is weak like (N=3, R=W=D=1) because the write operation will succeed once one replica is created on a leo_storage node (other two replicas will be created in async), that being said, if there are some replicas with only one copy and the leo_storage node which has those replicas goes down and never be back to the cluster then data lost happens.

> So, I want to know how Leofs's replica storage strategy is. 

I think the above comment answers your question. To be precise, the replica storage strategy depends on your consistency setting.
For example, If your consistency setting is (N=3, R=W=D=2) then the strategy can be though as `Quorum Based Replication` and if your consistency is (N=3, R=W=D=3) then the strategy can be though as `Primary Backup Replication`.

> And how to solve this problem.

If your consistency setting is weak then changing it to something medium like (N=3, R=W=D=2) might solve the problem.

If you want to recover the lost objects then let us know, if you still have the dropped node image then there might be the chance to get those objects recovered so we will tell you how to salvage lost data from dropped node image and ingest those back into the cluster.

**Comment by NewDund** [comment] 2018-08-31 08:17
My consistency settings are "n = 3, r = 1, w = 2, d = 2." My operation is just normal deletion of a storage node ("leofs-adm detach storage_01@x.x.x" and then "leofs-adm rebalance"), a total of four storage nodes, no error was reported, but I later traversed the whole of cluster and found data missing.

**Comment by NewDund** [comment] 2018-08-31 08:21
And here's another question. When rebalance executes, my intranet bandwidth is very high. Is there any settings that can be limited?

**Comment by mocchira** [comment] 2018-09-04 00:29
@NewDund 

> My consistency settings are "n = 3, r = 1, w = 2, d = 2." My operation is just normal deletion of a storage node ("leofs-adm detach storage_01@x.x.x" and then "leofs-adm rebalance"), a total of four storage nodes, no error was reported, but I later traversed the whole of cluster and found data missing.

The above procedure seems to be correct. however I heard from another commiter that you asked him about another question how to add the additional disk capacity to a leo_storage node and before asking him, you had already added a new disk partition to `obj_containers.(path|num_of_container)` in leo_storage.conf. Is it correct? if so then did you run `leofs-adm recover-node` on that node? Without issuing recover-node, you lost some object on that node. The reason why changing(adding) `obj_containers.*` can lose data are described on the below doc.

- https://leo-project.net/leofs/docs/admin/system_operations/data/#file-structure

Please read **Note: How files are distributed across the containers and AVS/KVS pairs?** section which allows you to understand why. and also please check the below doc out.

- https://leo-project.net/leofs/docs/admin/system_operations/data/#use-cases

The last section - **Scale up (Add an additional disk volume on LeoStorage)** explains the right way on how to add an additional disk volume on LeoStorage so if you didn't follow the instruction here, you might lose some data. If this is the case, let us know. If you sill haven't issued `leofs-adm compaction-start` on that node then there is a chance to salvage data from AVS files.

> And here's another question. When rebalance executes, my intranet bandwidth is very high. Is there any settings that can be limited?

- https://leo-project.net/leofs/docs/admin/settings/leo_storage/#leostorage-configurations

Lower num_of_batch_process_max,  mq.num_of_batch_process_regular (AND/OR)
Heighten mq.interval_between_batch_procs_max, mq.interval_between_batch_procs_regular can limit the rebalance operation's throughput so that would result in limiting the bandwidth.

**Comment by NewDund** [comment] 2018-09-04 02:14
I run the leofs-adm recover-node command after the storage node has added disks as normal. Maybe after the cluster is balanced, the data will be restored to integrity, but the production environment does not want any temporary loss of data. 
Similar environment is when I offline a storage node, in the execution of the leofs-adm rebalance command process, I do not want to read and write data problems, there is a solution?

**Comment by mocchira** [comment] 2018-09-04 03:22
> I run the leofs-adm recover-node command after the storage node has added disks as normal. Maybe after the cluster is balanced, the data will be restored to integrity, but the production environment does not want any temporary loss of data.
> Similar environment is when I offline a storage node, in the execution of the leofs-adm rebalance command process, I do not want to read and write data problems, there is a solution?

(I may misunderstand what you want to tell us. let me know if I wrongly interpreted your question)
With the proper settings and operations, any temporary loss of data almost never happen even while an offline storage node exists AND/OR rebalance is ongoing except multiple node failures. That being said, if you face any (temporary) loss of data then there should be something wrong operations OR bugs which is still unknown.

Can you share the full operation log in chronological order and when you noticed the loss of data also LeoFS cluster information in detail with us? It would be great if you follow the below template as much as you can.

- https://github.com/leo-project/leofs/wiki/template-of-an-issue-report

We are going to reproduce your problem on our testing environment by making it as much similar to your env as possible based on your answer.

**Comment by NewDund** [comment] 2018-09-04 04:48
This is my working directory.


When I run "uname -r”, I got "3.10.0-327.el7.x86_64”.My system version is Centos7.2. My leafs cluster version is 1.3.6. AndI have 4c8g resources.


I'll reiterate the problem. After the cluster is working properly, I'm importing data, and during that time I'm offline with a node and I find that some objects are not accessible.


原始邮件
发件人:yoshiyuki.kannonotifications@github.com
收件人:leo-project/leofsleofs@noreply.github.com
抄送:NewDundniudun@xiaozhu.com; Mentionmention@noreply.github.com
发送时间:2018年9月4日(周二) 11:22
主题:Re: [leo-project/leofs] Delete a storage node would cause data loss.(#1115)


I run the leofs-adm recover-node command after the storage node has added disks as normal. Maybe after the cluster is balanced, the data will be restored to integrity, but the production environment does not want any temporary loss of data.
 Similar environment is when I offline a storage node, in the execution of the leofs-adm rebalance command process, I do not want to read and write data problems, there is a solution?
(I may misunderstand what you want to tell us. let me know if I wrongly interpreted your question)
 With the proper settings and operations, any temporary loss of data almost never happen even while an offline storage node exists AND/OR rebalance is ongoing except multiple node failures. That being said, if you face any (temporary) loss of data then there should be something wrong operations OR bugs which is still unknown.
Can you share the full operation log in chronological order and when you noticed the loss of data also LeoFS cluster information in detail with us? It would be great if you follow the below template as much as you can.
https://github.com/leo-project/leofs/wiki/template-of-an-issue-report
We are going to reproduce your problem on our testing environment by making it as much similar to your env as possible based on your answer.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
从Foxmail发来的超大附件
leofs.tar.gz (80MB, 2018年10月4日 12:47到期)
进入下载页面

**Comment by NewDund** [comment] 2018-09-04 04:51
I have just replied to you in the form of mail, but I am not sure if you have received the mail and the attachment.

**Comment by mocchira** [comment] 2018-09-04 05:28
> I have just replied to you in the form of mail, but I am not sure if you have received the mail and the attachment.

I can confirm your comment however any attachments are not accessible on github so please attach files using github web UI if that includes detailed information. Current information you've given us is not enough to dig into further this problem.

One thing I have to confirm.
Given that your LeoFS version is quite old, this might cause the problem so give me some time to check if there is any serious bug <= 1.3.6.

**Comment by NewDund** [comment] 2018-09-04 05:40
This is my working directory for storage nodes.
https://github.com/NewDund/my_leofs
If you need any other documents or information, please let me know.

**Comment by mocchira** [comment] 2018-09-05 01:37
### What I got from your working direcory and some questions/recommendations to you
### leo_storage
- **"alarm_handler", ... {set,{system_memory_high_watermark,..."** can be found in info log files. That being said,  you may add some memory capacity on leo_storage nodes.
- The below log lines can be found in info log files. It seems you delete large files (OR update(overwrite) large files) in operation. Isn't it intentional delete ops? and also let me ask one more question. Have you used the multipart upload in case uploading jpg files? if so, is there any possibility that multiple clients try to upload the same file at the same time? if so, you may hit https://github.com/leo-project/leofs/issues/903#issuecomment-342571973. This issue has been fixed at 1.3.8.
```erlang
[I]	storage_01@10.0.1.106	2018-08-30 03:39:19.703307 +0800	1535571559	leo_storage_handler_del_directory:handle_call/3 - enqueue	149	[{"msg: enqueued",<<"xz-img-01/12,0,74,13457,3000,2000,45deb9f4.jpg\n">>}]
[I]	storage_01@10.0.1.106	2018-08-30 03:39:24.547922 +0800	1535571564	leo_storage_handler_del_directory:run/5	731	[{"msg: dequeued and removed (dir)",<<"xz-img-01/12,0,74,13457,3000,2000,45deb9f4.jpg\n">>}]
```
- The below log lines can be found in error log files. It seems you hit eleveldb related bugs LeoFS 1.3.6 had. This issue has been fixed at 1.4.0
```erlang
[E]	storage_01@10.0.1.106	2018-09-04 11:03:47.45039 +0800	1536030227	leo_backend_db_eleveldb:get/2	130	{badarg,[{eleveldb,async_get,[#Ref<0.0.262146.165052>,<<>>,<<"xz-img-01/12,0,46,8,801,801,2eedc55e.jpg">>,[]],[]},{eleveldb,get,3,[{file,"src/eleveldb.erl"},{line,164}]},{leo_backend_db_eleveldb,get,2,[{file,"src/leo_backend_db_eleveldb.erl"},{line,121}]},{leo_backend_db_server,handle_call,3,[{file,"src/leo_backend_db_server.erl"},{line,301}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```
- According to erlang.log.* files, you have had 7 disk volumes and used those as LeoFS' obj_containers.path and set obj_containers.num_of_containers to 32 on each. This setting will create 224 (7 * 32) obj_containers and so much obj_containers may load the disk utilization more than necessary so if leo_storage nodes on your cluster face high disk utilization then you may consider to decrease obj_containers.num_of_containers.
### leo_manager
- According to leo_manager.conf, your consistency setting says N=R=W=D=1. Isn't it correct?

### Serious problems found after 1.3.6
There has been three serious problems that can cause data loss.

- https://github.com/leo-project/leofs/issues/1021
- https://github.com/leo-project/leofs/issues/1017
- https://github.com/leo-project/leofs/issues/1014

You may hit any of three bugs. I suspect you would hit #1017 OR #1014 if you run leofs-adm compaction-start. If that's the case then I'd strongly recommend you upgrade LeoFS to the latest (1.4.2) in which all three bugs have been fixed.

**Comment by NewDund** [comment] 2018-09-05 10:41
I have upgraded to 1.4.2 version. But there are problems in the process of data import. 
when i run 'tail /usr/local/leofs/1.4.2/leo_gateway/log/app/error'
`[E]	gateway_01@10.0.1.103	2018-09-05 18:35:31.14806 +0800	1536143731	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:33.98483 +0800	1536143733	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:35.104699 +0800	1536143735	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:37.153870 +0800	1536143737	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:39.146775 +0800	1536143739	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:41.96705 +0800	1536143741	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:43.37750 +0800	1536143743	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:45.63873 +0800	1536143745	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:47.75161 +0800	1536143747	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}
[E]	gateway_01@10.0.1.103	2018-09-05 18:35:49.175241 +0800	1536143749	null:null	0	{module,"leo_s3_auth"},{function,"authenticate_5/1"},{line,434},{body,"get_credential rpc failed"}`

Meanwhile, my request returned to 503, but sometimes I can visit it normally. And my gateway looks normal. What is the reason?

**Comment by mocchira** [comment] 2018-09-06 02:00
@NewDund Just in case, I've confirmed the migration test from 1.3.6 to 1.4.2 and just works fine without any errors you are facing now. let me ask some questions

- Have you followed the migration instruction described on the official document here: https://leo-project.net/leofs/docs/admin/system_admin/migration/ ?
- Can you share the terminal log related to LeoFS migration operations with us?
- Can you share the config file of each component for 1.3.6 and also 1.4.2?

I think the error you are facing now could happen only in case you misconfigured `mnesia.dir` in the new leo_manager.conf. `mnesia.dir` in the new leo_manager.conf should refer to the same path as 1.3.6's one otherwise leo_gateway will fail to find the credential as error logs say.

**Comment by NewDund** [comment] 2018-09-06 02:47
I just uploaded all the configuration information and logs of 1.4.2 version.
https://github.com/NewDund/my_leofs/tree/master/1.4.2
But there is a little disappointed. I deleted everything from the old version. I'm sorry.
Is there any solution to the existing version?

**Comment by mocchira** [comment] 2018-09-06 05:05
@NewDund 

According to https://github.com/NewDund/my_leofs/blob/master/1.4.2/leo_manager_0/etc/leo_manager.conf#L121, you set `mnesia.dir` to the default relative path. That being said, as I mentioned at the previous commment,

> I think the error you are facing now could happen only in case you misconfigured mnesia.dir in the new leo_manager.conf. mnesia.dir in the new leo_manager.conf should refer to the same path as 1.3.6's one otherwise leo_gateway will fail to find the credential as error logs say.

This is why you are facing the error (get_credential rpc failed) because mnesia records storing credential information has been deleted.

> Is there any solution to the existing version?

- Create a new user using `leofs-adm create-user`
- Change the owner of a bucket using `leofs-adm chown-bucket` with access-key-id generated by the above command and buckets you have
- Distribute access-key-id/secret-access-key pair to the S3 clients connecting to LeoFS

Then

With new access-key-id/secret-access-key pair, all S3 clients will be able to connet to LeoFS without any errors like the one you are facing now.

Also let me say one more thing.

> Have you followed the migration instruction described on the official document here: https://leo-project.net/leofs/docs/admin/system_admin/migration/ ?

You didn't t answer the above question but Given that you removed all previous version's data, It seems you didn't follow the instruction described on the official document so please check out the document whenever you do some operations on LeoFS and also if you don't have the staging environment, I'd strongly recommend you build it and try every operation on the staging before doing the same operation on the production system in order to avoid any troubles.
I hope you find it helpful.

**Comment by NewDund** [comment] 2018-09-06 05:22
I did what you said.

> 
    Create a new user using leofs-adm create-user
    Change the owner of a bucket using leofs-adm chown-bucket with access-key-id generated by the above command and buckets you have
    Distribute access-key-id/secret-access-key pair to the S3 clients connecting to LeoFS

But there are still the same problems. I visited with Python.

> import boto
import boto.s3.connection

access_key = '0952a77e09742bac331e'
secret_key = 'c8a48b6aab6220474e6c5ad91befc893881ad411'
conn = boto.connect_s3(
aws_access_key_id = access_key,
aws_secret_access_key = secret_key,
host = '10.0.1.105', port = 80 ,
is_secure=False,
calling_format = boto.s3.connection.OrdinaryCallingFormat(),
)
bucket = conn.get_bucket('xz-img-01')

Is there any way to make the leofs cluster skip this error?

**Comment by mocchira** [comment] 2018-09-06 08:41
@NewDund Can you share the full error log files on leo_gateway? I'll look into further.

and also let me confirm that you probably lost the mnesia records which includes not only user credentials but buckets, endpoints and ACL information. Did you recover those records into the new cluster? if not then try to recover the records using leofs-adm add-endpoint, add-bucket and so on.

**Comment by NewDund** [comment] 2018-09-06 09:45
@mocchira All the configuration and log of my cluster are here now.
https://github.com/NewDund/my_leofs/tree/master/1.4.2
What I did during the upgrade was actually equivalent to restarting a new cluster. I emptied all the old versions of the data files and so on, so I didn't know what would happen if I started a new cluster like this.
The current error reports are "{module,'leo_s3_auth'}, {function,'authenticate_5/1'}, {line, 434}, {body,'get_credential RPC failed'}", but I do have access to AWS-S3 successfully.
But sometimes this error happens and I get 503.

**Comment by NewDund** [comment] 2018-09-06 10:31
@mocchira 
I found the answer. 
I found that there was always a 503 error report, but I returned to normal after the LB node ran "system CTL restart haproxy"
I came to the conclusion that if the cluster is restarted or stopped, the load balancing machine should restart.
I think this should be marked in the document. Thank you.

**Comment by mocchira** [comment] 2018-09-07 00:26
@NewDund Great to hear that you managed to fix your problem.

> I came to the conclusion that if the cluster is restarted or stopped, the load balancing machine should restart.
> I think this should be marked in the document. Thank you.

Generally speaking, It's always not true, it probably depends on your haproxy setting (and/or) how much time you took to upgrade (stop the old leo_gateway and start the new one). I will try some other scenarios and I will add the document if I think it's worth noting in the doc.

Anyway, please close the issue if every problem got clear now. If you still have some problem then let us know.

**Closed as completed** 2018-09-07 01:33 UTC
Labels: Question
