### ISSUE TITLE
leofs_storage start error 

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#872] opened 2017-10-11 03:13 UTC
leo_manager_0     Configuration :

manager.partner = manager_1@10.4.109.57
console.port.cui  = 10010
console.port.json = 10020
console.acceptors.cui = 3
console.acceptors.json = 16
console.histories.num_of_display = 200
system.dc_id = enn
system.cluster_id = ennleofs
consistency.num_of_replicas = 3
consistency.write = 3
consistency.read = 3
consistency.delete = 3
consistency.rack_aware_replicas = 0
mnesia.dir = ./work/mnesia/127.0.0.1
mnesia.dump_log_write_threshold = 50000
mnesia.dc_dump_limit = 40
rpc.server.acceptors = 16
rpc.server.listen_port = 13075
rpc.server.listen_timeout = 5000
rpc.client.connection_pool_size = 16
rpc.client.connection_buffer_size = 16
nodename = manager_0@10.4.108.109
distributed_cookie = 401321b4
erlang.kernel_poll = true
erlang.asyc_threads = 32
erlang.max_ports = 64000
erlang.crash_dump = ./log/erl_crash.dump
erlang.max_ets_tables = 256000
erlang.smp = enable
process_limit = 1048576

leo_manager_1   Configuration :

manager.partner = manager_0@10.4.108.109
console.port.cui  = 10011
console.port.json = 10021
console.acceptors.cui = 3
console.acceptors.json = 16
console.histories.num_of_display = 200
mnesia.dir = ./work/mnesia/127.0.0.1
mnesia.dump_log_write_threshold = 50000
mnesia.dc_dump_limit = 40
snmp_agent = ./snmp/snmpa_manager_1/LEO-MANAGER
rpc.server.acceptors = 16
rpc.server.listen_port = 13076
rpc.server.listen_timeout = 5000
rpc.client.connection_pool_size = 16
rpc.client.connection_buffer_size = 16
nodename = manager_1@10.4.109.57
distributed_cookie = 401321b4
erlang.kernel_poll = true
erlang.asyc_threads = 32
erlang.max_ports = 64000
erlang.crash_dump = ./log/erl_crash.dump
erlang.max_ets_tables = 256000
erlang.smp = enable
process_limit = 1048576

leo_storage   Configuration:  
managers = [manager_0@10.4.108.109, manager_1@10.4.109.57]
obj_containers.path = [/data/leofs]
obj_containers.num_of_containers = [8]
watchdog.common.loosen_control_at_safe_count = 1
watchdog.rex.is_enabled = true
watchdog.rex.interval = 10
watchdog.rex.threshold_mem_capacity = 33554432
watchdog.cpu.is_enabled = false
watchdog.cpu.raised_error_times = 5
watchdog.cpu.interval = 10
watchdog.cpu.threshold_cpu_load_avg = 5.0
watchdog.cpu.threshold_cpu_util = 100
watchdog.disk.is_enabled = false
watchdog.disk.raised_error_times = 5
watchdog.disk.interval = 10
watchdog.disk.threshold_disk_use = 85
watchdog.disk.threshold_disk_util = 90
watchdog.disk.threshold_disk_rkb = 98304
watchdog.disk.threshold_disk_wkb = 98304
watchdog.cluster.is_enabled = false
watchdog.cluster.interval = 10
watchdog.error.is_enabled = false
watchdog.error.interval = 60
watchdog.error.threshold_count = 100
autonomic_op.compaction.is_enabled = false
autonomic_op.compaction.parallel_procs = 1
autonomic_op.compaction.interval = 3600
autonomic_op.compaction.warn_active_size_ratio = 70
autonomic_op.compaction.threshold_active_size_ratio = 60
compaction.limit_num_of_compaction_procs = 4
compaction.waiting_time_regular = 500
compaction.waiting_time_max = 3000
compaction.batch_procs_regular = 1000
compaction.batch_procs_max = 1500
mq.num_of_mq_procs = 4
mq.num_of_batch_process_max = 3000
mq.num_of_batch_process_regular = 1600
mq.interval_between_batch_procs_max = 3000
mq.interval_between_batch_procs_regular = 500
replication.recovery.size_of_stacked_objs = 5242880
replication.recovery.stacking_timeout = 1
mdc_replication.size_of_stacked_objs = 33554432
mdc_replication.stacking_timeout = 30
mdc_replication.req_timeout = 30000
mdc_replication.stacking_procs = 1
log.log_level = 1
log.is_enable_diagnosis_log = true
leo_ordning_reda.send_after_interval = 0
mnesia.dump_log_write_threshold = 50000
mnesia.dc_dump_limit = 40
nodename = storage_01@10.4.110.35
distributed_cookie = 401321b4
erlang.kernel_poll = true
erlang.async_threads = 32
erlang.max_ports = 64000
erlang.crash_dump = ./log/erl_crash.dump
erlang.max_ets_tables = 256000
erlang.smp = enable
erlang.schedulers.compaction_of_load = true
erlang.schedulers.utilization_balancing = false
erlang.distribution_buffer_size = 32768
erlang.fullsweep_after = 0
erlang.secio = true
process_limit = 1048576

leofs_storage   start error   log  

heart_beat_kill_pid = 16361
Erlang/OTP 19 [erts-8.3.5.2] [source] [64-bit] [smp:1:1] [async-threads:32] [kernel-poll:true]

id:leo_logger_file_i, path:"./log/app", filename:"info"
* opening log file is /usr/local/leofs/1.3.7/leo_storage/log/app/info.20171010.23.1
id:leo_logger_file_e, path:"./log/app", filename:"error"
* opening log file is /usr/local/leofs/1.3.7/leo_storage/log/app/error.20171010.23.1
leo_backend_db_sup:131 - leo_metadata_7 {error,
                                         {enoent,
                                          {child,undefined,leo_metadata_7,
                                           {leo_backend_db_server,start_link,
                                            [leo_metadata_7,
                                             leo_backend_db_eleveldb,
                                             "/data/leofs/metadata/7",false]},
                                           permanent,2000,worker,
                                           [leo_backend_db_server]}}}
* closing log file is /usr/local/leofs/1.3.7/leo_storage/log/app/error.20171010.23.1
* closing log file is /usr/local/leofs/1.3.7/leo_storage/log/app/info.20171010.23.1
Eshell V8.3.5.2  (abort with ^G)
(storage_01@10.4.110.35)1> [os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,leo_storage,{bad_return,{{leo_storage_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{'EXI
T',invalid_launch},{child,undefined,leo_object_storage_sup,{leo_object_storage_sup,start_link,[[{8,\"/data/leofs\"}],leo_storage_msg_collector]},permanent,2000,superviso
r,[leo_object_storage_sup]}}}},[{leo_storage_app,launch_object_storage,1,[{file,\"src/leo_storage_app.erl\"},{line,292}]},{leo_storage_app,after_proc,1,[{file,\"src/leo_
storage_app.erl\"},{line,136}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,leo_storage,{bad_return,{{leo_storage_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{'EXIT
',invalid_launch},{child,undefi
heart: Tue Oct 10 23:04:33 2017: Erlang is crashing .. (waiting for crash dump file)
heart: Tue Oct 10 23:04:36 2017: Executed "/usr/local/leofs/1.3.7/leo_storage/bin/leo_storage start" -> 0. Terminating.

cat /usr/local/leofs/1.3.7/leo_storage/log/app/error.20171010.23.1
[E]	storage_01@10.4.110.35	2017-10-10 23:04:32.102772 -0400	1507691072	null:null	0	["CRASH REPORT ",[80,114,111,99,101,115,115,32,"<0.86.0>",32,119,105,116,104,32,"0",32,110,101,105,103,104,98,111,117,114,115,32,"exited",32,119,105,116,104,32,114,101,97,115,111,110,58,32,["enoent"," in ",[["gen_server",58,"init_it",47,"6"],[32,108,105,110,101,32,"344"]]]]]

system   version :  centos 7.2    3.10.0-514.el7.x86_64
leofs  version :  leofs-1.3.7-1.erl-19.3.el7.x86_64.rpm

**Comment by windkit** [comment] 2017-10-11 03:46
Could you provide more information about how you install, how you reproduce the situation?

**Comment by windkit** [comment] 2017-10-11 05:31
as the error message is "enoent" in `leo_storage`, please check if `/data/leofs` exists or not

**Comment by xingxing9688** [comment] 2017-10-11 06:21
The directory is there，
The last configuration was all the information I installed

**Comment by xingxing9688** [comment] 2017-10-11 06:38
![leofs_error](https://user-images.githubusercontent.com/23273577/31425410-d169294e-ae24-11e7-8599-7b6f5b4db9ea.jpg)

**Comment by xingxing9688** [comment] 2017-10-11 06:52
error  log  
Exec: /usr/local/leofs/1.3.7/leo_storage/erts-8.3.5.2/bin/erlexec -heart -boot /usr/local/leofs/1.3.7/leo_storage/releases/1/leo_storage
 -mode minimal -config /usr/local/leofs/1.3.7/leo_storage/etc/app.config -args_file /usr/local/leofs/1.3.7/leo_storage/etc/vm.args -- co
nsole
Root: /usr/local/leofs/1.3.7/leo_storage
heart_beat_kill_pid = 6676
Erlang/OTP 19 [erts-8.3.5.2] [source] [64-bit] [smp:1:1] [async-threads:32] [kernel-poll:true]

id:leo_logger_file_i, path:"./log/app", filename:"info"
* opening log file is /usr/local/leofs/1.3.7/leo_storage/log/app/info.20171011.02.1
id:leo_logger_file_e, path:"./log/app", filename:"error"
* opening log file is /usr/local/leofs/1.3.7/leo_storage/log/app/error.20171011.02.19
leo_backend_db_sup:131 - leo_metadata_7 {error,
                                         {enoent,
                                          {child,undefined,leo_metadata_7,
                                           {leo_backend_db_server,start_link,
                                            [leo_metadata_7,
                                             leo_backend_db_eleveldb,
                                             "/data/leofs/metadata/7",false]},
                                           permanent,2000,worker,
                                           [leo_backend_db_server]}}}
* closing log file is /usr/local/leofs/1.3.7/leo_storage/log/app/error.20171011.02.19
* closing log file is /usr/local/leofs/1.3.7/leo_storage/log/app/info.20171011.02.1
Eshell V8.3.5.2  (abort with ^G)
(storage_01@192.168.43.80)1> [os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,leo_storage,{bad_return,{{leo_storage_app,start,[normal,[]]}
,{'EXIT',{{badmatch,{error,{{'EXIT',invalid_launch},{child,undefined,leo_object_storage_sup,{leo_object_storage_sup,start_link,[[{8,\"/d
ata/leofs\"}],leo_storage_msg_collector]},permanent,2000,supervisor,[leo_object_storage_sup]}}}},[{leo_storage_app,launch_object_storage
,1,[{file,\"src/leo_storage_app.erl\"},{line,292}]},{leo_storage_app,after_proc,1,[{file,\"src/leo_storage_app.erl\"},{line,136}]},{appl
ication_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,leo_storage,{bad_return,{{leo_storage_app,start,[normal,[]]},
{'EXIT',{{badmatch,{error,{{'EXIT',invalid_launch},{child,undefi
heart: Wed Oct 11 02:48:45 2017: Erlang is crashing .. (waiting for crash dump file)



From here to see / data / leofs initialization of the metadata database，But the directory is there, there is no reporting error, in the end what is the cause of this error。

**Comment by windkit** [comment] 2017-10-11 07:34
is there a crashdump at `/usr/local/leofs/1.3.7/leo_storage/log/erl_crash.dump`? if there is one, could you upload it?

**Comment by xingxing9688** [comment] 2017-10-11 07:43
[leofs.tar.gz](https://github.com/leo-project/leofs/files/1374630/leofs.tar.gz)

**Comment by xingxing9688** [comment] 2017-10-11 08:07
The file system uses the xfs file system, according to   https://leo-project.net/leofs/docs-old/installation/install_2.html  

Do not know what causes the storage startup failed

**Comment by xingxing9688** [comment] 2017-10-11 08:23
![leofs-01](https://user-images.githubusercontent.com/23273577/31429322-570331ea-ae33-11e7-9e34-7783f3ad4344.jpg)

Why the server did not start up, the port is good

**Comment by xingxing9688** [comment] 2017-10-11 08:30
When the initialization process out, but do not know what the reasons, or parameters caused by

**Comment by xingxing9688** [comment] 2017-10-11 08:31
I now configure this configuration and 1.3.2 version of the same configuration, but not above 1.3.7 1.3.7 can be run in the production environment

**Comment by windkit** [comment] 2017-10-11 08:50
Please make sure the `/data/leofs/` is writable by user `leofs` as in 1.3.7, the process is run by a user `leofs`

**Comment by xingxing9688** [comment] 2017-10-11 09:00
Thank you, 1.3.7 really need to be authorized to the list of leofs users can, and 1.3.2 changes

**Comment by xingxing9688** [comment] 2017-10-11 09:07
Hello, find an increase in that version, I did not find this function in CHANGELOG increase

**Comment by windkit** [comment] 2017-10-11 09:24
@yosukehara @mocchira 
To summarize this issue, it is caused by the permission problem in `leo_backend_db:open`
The change of running user to `leofs` is hard to notice and sadly the error message from `eleveldb:open` returns a `enoent` instead of `eaccess` in this case.
(when the directory exists but not writtable, here the `/data/leofs` exists but is not writable by user `leofs`)

**Comment by xingxing9688** [comment] 2017-10-11 09:37
Thank you！
leofs_storage
Start time, the initialization time, the log error is not obvious, you need to optimize, I see this error, simply can not find what is caused by the cause.

**Comment by mocchira** [comment] 2017-10-12 00:32
@windkit thanks for summarizing. let me correct one thing

> The change of running user to leofs is hard to notice and sadly the error message from eleveldb:open returns a enoent instead of eaccess in this case.

Not true as eleveldb:open never returns enoent.
Now I suspect filelib:ensure_dir returns enoent at https://github.com/leo-project/leo_backend_db/blob/1.2.20/src/leo_backend_db_server.erl#L487-L496 because https://github.com/erlang/otp/blob/OTP-20.1.1/lib/stdlib/src/filelib.erl#L239 ensure_dir ignores the error when the recursive call fails so it returns only the result of final make_dir.

It might be difficult(impossible for some reason) and take time to bring the fix into upstream, I will add leo_file:ensure_dir in leo_commons with the fix returning the error happened at the first place(eaccess get to return) and use it here instead of filelib:ensure_dir.

**Comment by mocchira** [comment] 2017-10-26 01:37
TODO: 
- [x] Impl leo_file:ensure_dir in leo_commons
- [ ] Call leo_file:ensure_dir where filelib:ensure_dir called now

**Comment by mocchira** [comment] 2017-11-02 07:00
- https://github.com/leo-project/leo_object_storage/pull/15
- https://github.com/leo-project/leo_backend_db/pull/14

Once the above two PR get merged, I'll close this issue.

**Closed** 2017-11-06 23:45 UTC
Labels: Improve, Priority-MIDDLE, _leo_commons, _leo_object_storage
