### ISSUE TITLE
[1.2][1.4][leo_storage] Node Stopped with Many Small Write Requests

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#443] opened 2016-02-03 04:46 UTC
### Description
During a benchmark with cosbench, storage node stopped in the middle.
The workload was configured as 100% write of 4KB Objects with 64 Workers across 4 Drivers
At first, it ran well with good throughput >15000 ops (60MB/s) but then failed to serve the requests
![cosbench](https://cloud.githubusercontent.com/assets/360884/12773017/a30dd3a4-ca7a-11e5-9ee0-7e4c6c5aebe1.jpg)

### Environment
LeoFS Version: 1.4.0-pre3 (Erlang 17.5)
LeoFS Setup: 1x Gateway, 5 x Storage
LeoFS Configuration: [conf.tar.gz](https://github.com/leo-project/leofs/files/115121/conf.tar.gz)
OS: Ubuntu 14.04.3 x64
Hardware: Xeon E5-2630 v3, 32GB Ram, (Storage) 6x 15k sas HDD, RAID-0

### Error Logs / Crashdump
Error Log: [error.txt](https://github.com/leo-project/leofs/files/115122/error.txt)
Trimmed Crashdump (Uncompressed 3GB): [snap.dump](https://drive.google.com/file/d/0B26vAI5J5Wrhbm03OFNzYnFvMW8/view?usp=sharing)

### Observation
Many processes are staled at `mnesia_tm:rec/2` which initialized from `leo_sync_remote_cluster:defer_stack/1`.
Commented out the whole method actually get rid of the issue and the benchmark could complete

**Comment by windkit** [comment] 2016-02-03 04:48
Error Log
```
[E]     S0@192.168.100.36       2016-02-03 09:59:34.345367 +0900        1454461174      null:null       0       Mnesia('S0@192.168.100.36'): ** WARNING ** Mnesia is overloaded: {mnesia_tm,message_queue_len,[50256,153217]}
[E]     S0@192.168.100.36       2016-02-03 09:59:34.345798 +0900        1454461174      null:null       0       gen_event mnesia_event installed in mnesia_event terminated with reason: bad argument in call to ets:lookup(global_names, mnesia_global_logger) in global:where/1 line 1230
[E]     S0@192.168.100.36       2016-02-03 10:01:02.288481 +0900        1454461262      null:null       0       Too many processes
[E]     S0@192.168.100.36       2016-02-03 10:01:02.288690 +0900        1454461262      null:null       0       Too many processes
[E]     nonode@nohost   2016-02-03 10:01:02.624160 +0900        1454461262      null:null       0       Too many processes
[E]     nonode@nohost   2016-02-03 10:01:02.628741 +0900        1454461262      null:null       0       gen_server leo_storage_event_notifier terminated with reason: {system_limit,[{erlang,spawn,[erlang,apply,[#Fun<leo_sync_remote_cluster.0.76708156>,[]]],[]},{erlang,spawn,1,[]},{leo_sync_remote_cluster,defer_stack,1,[{file,"src/leo_sync_remote_cluster.erl"},{line,74}]},{leo_storage_event_notifier,handle_call,3,[{file,"src/leo_storage_event_notifier.erl"},{line,115}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
[E]     nonode@nohost   2016-02-03 10:01:02.629477 +0900        1454461262      null:null       0       Too many processes
[E]     nonode@nohost   2016-02-03 10:01:02.630438 +0900        1454461262      null:null       0       gen_server rex terminated with reason: {system_limit,[{erlang,spawn_opt,[{erlang,apply,[#Fun<rpc.1.116928089>,[]],[monitor]}],[]},{erlang,spawn_monitor,1,[]},{rpc,handle_call_call,6,[{file,"rpc.erl"},{line,199}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
[E]     nonode@nohost   2016-02-03 10:01:02.632019 +0900        1454461262      null:null       0       ["CRASH REPORT ",[80,114,111,99,101,115,115,32,"rex",32,119,105,116,104,32,"0",32,110,101,105,103,104,98,111,117,114,115,32,"exited",32,119,105,116,104,32,114,101,97,115,111,110,58,32,[[123,["system_limit",44,[91,[[123,["erlang",44,"spawn_opt",44,[91,[[123,["erlang",44,"apply",44,[91,["#Fun<rpc.1.116928089>",44,"[]"],93],44,[91,["monitor"],93]],125]],93],44,"[]"],125],44,[123,["erlang",44,"spawn_monitor",44,"1",44,"[]"],125],44,[123,["rpc",44,"handle_call_call",44,"6",44,[91,[[123,["file",44,"\"rpc.erl\""],125],44,[123,["line",44,"199"],125]],93]],125],44,[123,["gen_server",44,"try_handle_call",44,"4",44,[91,[[123,["file",44,"\"gen_server.erl\""],125],44,[123,["line",44,"607"],125]],93]],125],44,[123,["gen_server",44,"handle_msg",44,"5",44,[91,[[123,["file",44,"\"gen_server.erl\""],125],44,[123,["line",44,"639"],125]],93]],125],44,[123,["proc_lib",44,"init_p_do_apply",44,"3",44,[91,[[123,["file",44,"\"proc_lib.erl\""],125],44,[123,["line",44,"237"],125]],93]],125]],93]],125]," in ",[["gen_server",58,"terminate",47,"7"],[32,108,105,110,101,32,"804"]]]]]
[E]     nonode@nohost   2016-02-03 10:01:02.633219 +0900        1454461262      null:null       0       Supervisor kernel_sup had child rex started with rpc:start_link() at <0.416.0> exit with reason {system_limit,[{erlang,spawn_opt,[{erlang,apply,[#Fun<rpc.1.116928089>,[]],[monitor]}],[]},{erlang,spawn_monitor,1,[]},{rpc,handle_call_call,6,[{file,"rpc.erl"},{line,199}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]} in context child_terminated
[E]     nonode@nohost   2016-02-03 10:01:02.633930 +0900        1454461262      null:null       0       Supervisor kernel_sup had child rex started with rpc:start_link() at <0.416.0> exit with reason reached_max_restart_intensity in context shutdown
[E]     nonode@nohost   2016-02-03 10:01:02.635260 +0900        1454461262      null:null       0       ["CRASH REPORT ",[80,114,111,99,101,115,115,32,"leo_storage_event_notifier",32,119,105,116,104,32,"0",32,110,101,105,103,104,98,111,117,114,115,32,"exited",32,119,105,116,104,32,114,101,97,115,111,110,58,32,[[123,["system_limit",44,[91,[[123,["erlang",44,"spawn",44,[91,["erlang",44,"apply",44,[91,["#Fun<leo_sync_remote_cluster.0.76708156>",44,"[]"],93]],93],44,"[]"],125],44,[123,["erlang",44,"spawn",44,"1",44,"[]"],125],44,[123,["leo_sync_remote_cluster",44,"defer_stack",44,"1",44,[91,[[123,["file",44,"\"src/leo_sync_remote_cluster.erl\""],125],44,[123,["line",44,"74"],125]],93]],125],44,[123,["leo_storage_event_notifier",44,"handle_call",44,"3",44,[91,[[123,["file",44,"\"src/leo_storage_event_notifier.erl\""],125],44,[123,["line",44,"115"],125]],93]],125],44,[123,["gen_server",44,"try_handle_call",44,"4",44,[91,[[123,["file",44,"\"gen_server.erl\""],125],44,[123,["line",44,"607"],125]],93]],125],44,[123,["gen_server",44,"handle_msg",44,"5",44,[91,[[123,["file",44,"\"gen_server.erl\""],125],44,[123,["line",44,"639"],125]],93]],125],44,[123,["proc_lib",44,"init_p_do_apply",44,"3",44,[91,[[123,["file",44,"\"proc_lib.erl\""],125],44,[123,["line",44,"237"],125]],93]],125]],93]],125]," in ",[["gen_server",58,"terminate",47,"7"],[32,108,105,110,101,32,"804"]]]]]
[E]     nonode@nohost   2016-02-03 10:01:02.637045 +0900        1454461262      null:null       0       Supervisor leo_storage_sup had child leo_storage_event_notifier started with leo_storage_event_notifier:start_link() at <0.82.0> exit with reason {system_limit,[{erlang,spawn,[erlang,apply,[#Fun<leo_sync_remote_cluster.0.76708156>,[]]],[]},{erlang,spawn,1,[]},{leo_sync_remote_cluster,defer_stack,1,[{file,"src/leo_sync_remote_cluster.erl"},{line,74}]},{leo_storage_event_notifier,handle_call,3,[{file,"src/leo_storage_event_notifier.erl"},{line,115}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]} in context child_terminated
[E]     nonode@nohost   2016-02-03 10:01:02.637873 +0900        1454461262      null:null       0       gen_server snmpa_local_db terminated with reason: {shutdown,{gen_server,call,[kernel_safe_sup,{start_child,{dets_sup,{dets_sup,start_link,[]},permanent,1000,supervisor,[dets_sup]}},infinity]}} in gen_server:call/3 line 190
[E]     nonode@nohost   2016-02-03 10:01:02.638218 +0900        1454461262      null:null       0       Supervisor snmpa_supervisor had child snmpa_local_db started with snmpa_local_db:start_link(normal, "snmp/snmpa_storage_0/db", terminate, []) at <0.616.0> exit with reason {shutdown,{gen_server,call,[kernel_safe_sup,{start_child,{dets_sup,{dets_sup,start_link,[]},permanent,1000,supervisor,[dets_sup]}},infinity]}} in context child_terminated
[E]     nonode@nohost   2016-02-03 10:01:02.638507 +0900        1454461262      null:null       0       Supervisor snmpa_supervisor had child snmpa_local_db started with snmpa_local_db:start_link(normal, "snmp/snmpa_storage_0/db", terminate, []) at <0.616.0> exit with reason reached_max_restart_intensity in context shutdown
[E]     nonode@nohost   2016-02-03 10:01:02.638742 +0900        1454461262      null:null       0       Supervisor snmp_app_sup had child snmpa_supervisor started with snmpa_supervisor:start_link(normal, [{versions,[v1,v2]},{db_dir,"snmp/snmpa_storage_0/db"},{config,[{dir,"snmp/snmpa_storage_0/agen..."},...]},...]) at <0.613.0> exit with reason shutdown in context child_terminated
[E]     nonode@nohost   2016-02-03 10:01:02.638974 +0900        1454461262      null:null       0       Supervisor snmp_app_sup had child snmpa_supervisor started with snmpa_supervisor:start_link(normal, [{versions,[v1,v2]},{db_dir,"snmp/snmpa_storage_0/db"},{config,[{dir,"snmp/snmpa_storage_0/agen..."},...]},...]) at <0.613.0> exit with reason reached_max_restart_intensity in context shutdown
[W]     nonode@nohost   2016-02-03 10:01:02.645326 +0900        1454461262      leo_sync_remote_cluster:defer_stack/1   99      [{key,"test1/myobjects412"},{cause,{aborted,{no_exists,[ram_copies,leo_cluster_stat,[{'$1',[{'==',{element,3,'$1'},{const,running}}],['$1']}],100]}}}]
```

**Comment by yosukehara** [comment] 2016-02-03 05:18
Thanks for your report. I've confirmed the crashdump with the crashdump_viewer as below:

<img width="850" alt="screen shot 2016-02-03 at 14 09 43" src="https://cloud.githubusercontent.com/assets/148770/12773621/c8a6c296-ca80-11e5-8a19-f297a77a0cbe.png">

As you can see on this result,  this node generated many processes and allocated much memory.

**Comment by yosukehara** [comment] 2016-02-03 08:59
Here is a chart of monitoring during a benchmark:

![monitoring](https://cloud.githubusercontent.com/assets/148770/12777370/c887721e-ca9f-11e5-8da2-f3c7e0b22792.jpg)

**Comment by windkit** [comment] 2016-02-04 01:51
### Monitoring with entop

#### 4KB Test (Crashed)
![begin](https://cloud.githubusercontent.com/assets/360884/12803288/aa3a5a64-cb2c-11e5-95af-1196f40af6df.jpg)
![crashed](https://cloud.githubusercontent.com/assets/360884/12803289/aa3bf734-cb2c-11e5-8734-00c688d6a61c.jpg)

#### 128KB~1MB R:W 49:1 Benchmark (Normal)
![normal](https://cloud.githubusercontent.com/assets/360884/12803295/b6774008-cb2c-11e5-9c8b-9e5536e2b9e7.jpg)

### Observation
In the crashed case, the number of processes would keep increasing from the beginning. While in normal case, the number of processes stay around 560

As confirmed with the crashdump and the entop result, many processes are staled around `mnesia_tm`

**Comment by windkit** [comment] 2016-02-04 01:54
To reproduce the issue, a high IOPS loading seems necessary.

### Guess
It seems mnesia cannot keep up with the large number of transactional read/write and therefore functions spawn at `leo_sync_remote_cluster/defer_stack/1` would accumulate and eventually exhaust the number of processes in the VM.

**Comment by yosukehara** [comment] 2016-02-04 13:13
I've recognized this issue has happened in v1.2 and v1.4.0-pre3. I've fixed it which restrain accessing mnesia. We'll check this issue on our environment again whether we really solved it or not.

**Comment by windkit** [comment] 2016-02-05 00:08
With the fix, part of the issue is fixed, the number of processes would be lower to <100k
But still it looks problematic and this time the process is killed by OS with out of memory
```
[1180786.707216] Out of memory: Kill process 51026 (beam.smp) score 983 or sacrifice child
[1180786.707475] Killed process 51026 (beam.smp) total-vm:114894912kB, anon-rss:31481236kB, file-rss:0kB
```

`Grafana` screenshot along the test
![dashboard 1 4 fix](https://cloud.githubusercontent.com/assets/360884/12833946/4c139ade-cbe7-11e5-9a1a-cf2b77b9305d.png)

`entop` screenshot in the end, `S3@192.168.100.39` failed to respond.
![10](https://cloud.githubusercontent.com/assets/360884/12833874/ccaa43d8-cbe6-11e5-95ed-06170c8e2bac.png)

I will continue to test 1.2.18 and will try to obtain a crashdump for 1.4-pre3 afterwards

**Comment by yosukehara** [comment] 2016-02-05 00:16
@windkit Thanks for testing v1.4.0-pre3. I'll check **leo_stroage v1.4 branch** to find other bugs.

**Comment by windkit** [comment] 2016-02-05 00:49
Result for 1.2.18 looks normal

![1 2 18-fix](https://cloud.githubusercontent.com/assets/360884/12834767/9190cdc4-cbed-11e5-8af9-e2e77ae07ccc.png)

**Comment by yosukehara** [comment] 2016-02-05 03:32
I've shared a screenshot of ``crashdump_viewer`` of a crashed node as below.
It seems ``leo_storage_replicator_cp`` generated many processes, and which were not terminated.

![crashdump_viewer_screenshot 001](https://cloud.githubusercontent.com/assets/148770/12837205/885e940a-cc03-11e5-9303-1b30f226858f.jpeg)

**Comment by windkit** [comment] 2016-02-05 04:43
@yosukehara Agree.

A simple fix could be removing the `spawn` at `leo_storage_replicator_cp:replicate_1`
![dashboard attempt](https://cloud.githubusercontent.com/assets/360884/12838117/163448a2-cc0d-11e5-98a9-8bdf81e22821.png)
I started the `basho_bench` and then stopped it after 20 minutes.

(After another 10minutes)
Now, at least, nodes are surviving and seems that they are working very hard to clear the message queue slowly...... (looks like a single-threaded process, keep 100% CPU)
`entop` screenshot
![s3](https://cloud.githubusercontent.com/assets/360884/12838159/ab00c1f4-cc0d-11e5-8453-bccb6bb74389.png)
![s3_2](https://cloud.githubusercontent.com/assets/360884/12838170/d9857aba-cc0d-11e5-844f-09336e2b4fcc.png)

I think we need a better mechanism for replication.

**Comment by windkit** [comment] 2016-02-05 04:49
But isn't it the same mechanism in 1.2 series?

**Comment by yosukehara** [comment] 2016-02-05 05:03
@windkit v1.4.0's replicator is little bit different from v1.2.

**Comment by windkit** [comment] 2016-02-05 06:24
![entop](https://cloud.githubusercontent.com/assets/360884/12839413/6c63edb8-cc1c-11e5-82bb-d97acd7c5ddb.png)
![mq](https://cloud.githubusercontent.com/assets/360884/12839416/70968c6a-cc1c-11e5-9b2c-fe9d4b7c65ae.png)
Updated screenshot with more verbose output (same as above, I removed the 'spawn' at 'leo_storage_replicator_cp:replicate_1'

**Comment by yosukehara** [comment] 2016-02-05 06:28
@windkit Thanks, I got it. The root cause is [leo_directory_event](https://github.com/leo-project/leo_storage/blob/1.4/src/leo_directory_event.erl). I'll check it from now.

**Comment by windkit** [comment] 2016-02-05 08:12
@yosukehara I confirm the issue is fixed with the commit.

![dashboard fixed 1 4](https://cloud.githubusercontent.com/assets/360884/12841028/90655c2e-cc2b-11e5-9eb4-4906f1b13876.png)

**Comment by yosukehara** [comment] 2016-02-05 09:04
@windkit I've fixed all of problems, then closed this issue.
In addition, I’ll consider implementation of the synchronization of directory-metadatas to improve v1.4's performance.

**Comment by yosukehara** [comment] 2016-03-08 03:15
We have reproduce this situation the development-branch of LeoStorage.

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-1457406729907](https://cloud.githubusercontent.com/assets/148770/13590927/6084d9fc-e527-11e5-9725-973b10d5bc34.png)

**Comment by yosukehara** [comment] 2016-03-08 07:42
We've confirmed that we fixed this issue:

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-1457417442090](https://cloud.githubusercontent.com/assets/148770/13595198/aae1e9fc-e54c-11e5-8d7f-6994e695b621.png)

**Closed by yosukehara** 2016-03-08 07:42 UTC
Labels: Bug, Test, _leo_storage
