### ISSUE TITLE
LeoFS big size object copy operation seems very slow 

### ISSUE THREAD

**Issue by PatelParas** [leo-project/leofs#424] opened 2015-10-13 08:37 UTC
LeoFS v.1.2.11
we use in PROD environment. According to current and future use cases we need to perform more and rename or move operation for all small size and big size object. move or rename use cases are increasing exponentially in our system becuase.
 basically aws s3 don't have rename object method so we do it in following manner :
```
## To rename or move object A to B
Step - 1 : CopyObject(A,B)
Step -2 : removeObject(A)
```
but for large size object just in case copyObject() (takes 6 second) + deleteObject(1 second or less). it looks file rename is too slow(User feel it).

so it will be great if you improve large object copy method's implementation either of this way :

1) Make chunk copy operation using parallel thread(current implementation is serial thread copy) using this we can make copy operation fundamentally faster.

2) If previous proposal is not feasible to implement  then make copyObject() asynchronous(don't wait for copy operation completion put it as background job or queue) 

Above is just my suggestion i don't have idea of technical feasibility or complexity of this erlang system implementation. but please improve large object copy performance if rename operation looks slow it makes bad impact on user's mind.

**Comment by yosukehara** [comment] 2015-10-13 08:58
@PatelParas Thank you for your report. We'll check the copy processing whether we're able to reproduce this situation or not.

**Comment by mocchira** [comment] 2015-10-29 01:59
@PatelParas 
I wouldn't recommend you choosing 1) since the network speed of your PROD environment seems relatively slow, so probably not effective.
So we consider 2) approach but we think this kind of tasks(do async something) should be done at application layer, since providing async operations make LeoFS complex more than necessary as a object storage system.
How is this?

**Comment by PatelParas** [comment] 2015-11-04 01:48
What do you think ? first let me check object copy behavior in amazon S3. if they take similar long time to copy object then we don't need to change anything i need to consider implementation on application layer.

Our DEV and STG Storage disk have some IOPS limitation then it was previous issue but we are now migrating to openstack which have high IOPS and about PROD environment we use SSD of Hitachi and Seagate  so i don't think it have lower performance.

**Comment by mocchira** [comment] 2015-11-04 03:43
@PatelParas 

> first let me check object copy behavior in amazon S3.

Thanks.
Please let us know after getting the result.

To make sure,
I' ll describe the LeoFS behavior when doing copy a large object.

1. GW get a metadata and find out how many chunks there are.
2. GW get a chunk
3. GW put a chunk to a new destination
4. repeat 2,3 untif EOF

> Our DEV and STG Storage disk have some IOPS limitation then it was previous issue but we are 
> now migrating to openstack which have high IOPS and about PROD environment we use SSD of 
> Hitachi and Seagate so i don't think it have lower performance.

I mean that the network transfer rate might be slow in your env, 
if the issue filed at https://github.com/leo-project/leofs/issues/429 happen on your env.

**Comment by yosukehara** [comment] 2016-01-05 07:44
We've closed this issue. If you have any questions and comments, please let us know.

**Closed by yosukehara** 2016-01-05 07:44 UTC
Labels: Improve, _leo_gateway
