### ISSUE TITLE
transfer-encoding: identity in https://github.com/leo-project/cowboy/

### ISSUE THREAD

**Issue by zhjunqin** [leo-project/leofs#489] opened 2016-08-19 05:36 UTC
Hi,

I found a problem when I use LeoFS s3 as input and ouput of Hadoop job.
Hadoop always report following problem when I run MapReduce Job.

`Caused by: org.apache.http.ProtocolException: Transfer-encoding header already present`

Then I found there are two very close HEAD requests sent from Hadoop.
![image](https://cloud.githubusercontent.com/assets/7519482/17799739/a8631e6e-660f-11e6-8e36-10851897851b.png)

LeoFS response same message with transfer-encoding: identity
![image](https://cloud.githubusercontent.com/assets/7519482/17799791/31fca6cc-6610-11e6-9f38-1d2ca1213a57.png)

Then I looked into LeoFS and found in https://github.com/leo-project/cowboy/blob/master/src/cowboy_req.erl,

```
    Req3 = case Body of
        BodyFun when is_function(BodyFun) ->
            %% We stream the response body until we close the connection.
            RespConn = close,
            {RespType, Req2} = if
                Transport =:= cowboy_spdy ->
                    response(Status, Headers, RespHeaders, [
                        {<<"date">>, cowboy_clock:rfc1123()},
                        {<<"server">>, <<"Cowboy">>}
                    ], stream, Req);
                true ->
                    response(Status, Headers, RespHeaders, [
                        {<<"connection">>, <<"close">>},
                        {<<"date">>, cowboy_clock:rfc1123()},
                        {<<"server">>, <<"Cowboy">>},
                        {<<"transfer-encoding">>, <<"identity">>}
                    ], <<>>, Req)
            end,
            if  RespType =/= hook, Method =/= <<"HEAD">> ->
                    BodyFun(Socket, Transport);
                true -> ok
            end,
```

Cowboy in LeoFS add {<<"transfer-encoding">>, <<"identity">>} in response.
After I removed the line, Hadoop works well with LeoFS through S3a.

Then I did following check.
First, I compared the Response form Amazon S3 with LeoFS and found none of response message from Amazon S3 with the element transfer-encoding: identity.
Second, I searched Cowboy in https://github.com/ninenines/cowboy, there is no such code in it.

So, could you help check the code line is really necessary? Any background?
Thank you very much!

BTW. I use the develop branch following guide in https://github.com/leo-project/leofs to install LeoFS.

**Comment by windkit** [comment] 2016-08-19 06:33
Cowboy has undergone much development to support HTTP/2 the code is removed around the time.
We may need to consider updating the cowboy version or hacking around this.

Thanks for reporting.

**Comment by mocchira** [comment] 2016-12-07 08:44
Cowboy has been correct. (but a little bit lazy)
LeoFS has been wrong when responding to HEAD ;)

The reason why hadoop complain is 
there is a Content-Length added by LeoFS and also Transfer-Encoding added by Cowboy if the Body argument type is func() and coexisting both of them is prohibited in the protocol spec.

https://github.com/leo-project/leo_gateway/blob/1.3.0/src/leo_gateway_http_commons.erl#L809

We need to fix the above line with simple cowboy:req_reply
(set `<<>>` to the Body argument instead of an empty anonymous func).

**Comment by windkit** [comment] 2016-12-09 06:26
@mocchira The fix actually breaks with aws-sdk-java 1.9.40.
As it expect the content length field is "Content-Length" instead of "content-length".

**Comment by yosukehara** [comment] 2016-12-09 08:22
@windkit @mocchira [aws-sdk-java 1.9.40](https://github.com/aws/aws-sdk-java/releases/tag/1.9.40) is very old, we need to announce support version of it as well as other clients on the documentation and others.

**Comment by windkit** [comment] 2016-12-12 01:15
Seems aws-sdk-java 1.11.66 is fine with the change, I am updating the `leofs_client_tests`

**Comment by windkit** [comment] 2016-12-20 06:05
As S3 SPI Support for Hadoop is built against aws-sdk-java 1.7.4, the departure from camel case broke the link.

Case-insensitive is the standard yet in the old days people used camel case as the de facto standard (I suspect that's the IE to blame)

**Comment by mocchira** [comment] 2016-12-20 06:32
@windkit thank you for confirming that.
so the only way to solve this problem may be to add an additional patch to our homegrown cowboy to respond camel case headers.
could you patch like this?

**Comment by windkit** [comment] 2016-12-21 00:49
@mocchira Yes, I will patch the cowboy with that. Basically convert all headers to camel case.

**Comment by windkit** [comment] 2016-12-26 09:25
@mocchira Here I modify the `cowboy_req:merge_headers` so it would first convert the headers to camel case and then merge.

New problem with old `aws-sdk-java` is it assumes camel cased headers EXCEPT (?!) ETag.

So it is excluded in the process, Custom Metadata related is also excluded to pass through the content

**Comment by windkit** [comment] 2016-12-26 09:26
https://github.com/leo-project/cowboy/pull/1

**Comment by yosukehara** [comment] 2017-01-17 13:08
leo-project/cowboy/pull/1 was merged, then we need to test this to include its fix into [LeoFS v1.3.2](https://github.com/leo-project/leofs/milestone/59).

**Comment by windkit** [comment] 2017-01-18 01:47
Confirmed the PR is compatible with `aws-sdk-java 1.9.40` and `aws-sdk-java 1.7.4`

**Comment by yosukehara** [comment] 2017-01-26 01:02
We tested the latest LeoFS' development with `aws-sdk-java 1.9.40` and `aws-sdk-java 1.7.4`, and we recognized there is no issue. I'm going to close it.

**Closed by yosukehara** 2017-01-26 01:02 UTC
Labels: Bug, Priority-MIDDLE, v1.3, _leo_gateway
