### ISSUE TITLE
[leo_gateway] Missing "Last-Modified" in response of range GET

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#411] opened 2015-07-30 03:54 UTC
The HTTP Header "Last-Modified" is not set in response to Range GET request

It causes problem with jclouds which would parse the "Last-Modified"
```bash
     [java] Caused by: org.jclouds.http.HttpException: Last-Modified header not present in response: {statusCode=206, message=Partial Content, headers={date=[Thu, 30 Jul 2015 03:33:34 GMT], server=[LeoFS], connection=[keep-alive]}, payload=[content=true, contentMetadata=[contentDisposition=null, contentEncoding=null, contentLanguage=null, contentLength=4, contentMD5=null, contentType=application/octet-stream, expires=null], written=false]}
     [java] 	at org.jclouds.blobstore.functions.ParseSystemAndUserMetadataFromHeaders.parseLastModifiedOrThrowException(ParseSystemAndUserMetadataFromHeaders.java:92)
     [java] 	at org.jclouds.blobstore.functions.ParseSystemAndUserMetadataFromHeaders.apply(ParseSystemAndUserMetadataFromHeaders.java:72)
     [java] 	at org.jclouds.s3.functions.ParseObjectMetadataFromHeaders.apply(ParseObjectMetadataFromHeaders.java:61)
     [java] 	at org.jclouds.s3.functions.ParseObjectFromHeadersAndHttpContent.apply(ParseObjectFromHeadersAndHttpContent.java:48)
     [java] 	at org.jclouds.s3.functions.ParseObjectFromHeadersAndHttpContent.apply(ParseObjectFromHeadersAndHttpContent.java:34)
     [java] 	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
     [java] 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
     [java] 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
     [java] 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
     [java] 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
     [java] 	at com.sun.proxy.$Proxy42.getObject(Unknown Source)
     [java] 	at org.jclouds.s3.blobstore.S3BlobStore.getBlob(S3BlobStore.java:233)
     [java] 	at LeoFSTest.rangeObject(Unknown Source)
```

probably need fix to `leo_gateway_http_common:get_range_object/4`

**Comment by yosukehara** [comment] 2015-07-30 05:44
Thanks for your report. I'll check this issue.

**Comment by yosukehara** [comment] 2015-08-10 00:50
I've fixed this issue.  The test log is as below:

## Before
```bash
$ curl --range 0-99 http://test.localhost:8080/LeoFS.pdf -o /dev/null -v
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* Connected to test.localhost (127.0.0.1) port 8080 (#0)
> GET /LeoFS.pdf HTTP/1.1
> Range: bytes=0-99
> User-Agent: curl/7.37.1
> Host: test.localhost:8080
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< connection: keep-alive
< date: Mon, 10 Aug 2015 00:16:52 GMT
< Content-Length: 100
* Server LeoFS is not blacklisted
< server: LeoFS
< Content-Type: application/pdf
<
{ [data not shown]
100   100  100   100    0     0  12551      0 --:--:-- --:--:-- --:--:-- 14285
* Connection #0 to host test.localhost left intact
```


## After
```bash
$ curl --range 0-99 http://test.localhost:8080/LeoFS.pdf -o /dev/null -v
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* Connected to test.localhost (127.0.0.1) port 8080 (#0)
> GET /Cockroach.pdf HTTP/1.1
> Range: bytes=0-99
> User-Agent: curl/7.37.1
> Host: test.localhost:8080
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< connection: keep-alive
< date: Mon, 10 Aug 2015 00:44:43 GMT
< Content-Length: 100
* Server LeoFS is not blacklisted
< server: LeoFS
< Content-Type: application/pdf
< Last-Modified: Mon, 10 Aug 2015 00:43:14 GMT
<
{ [data not shown]
100   100  100   100    0     0  12423      0 --:--:-- --:--:-- --:--:-- 14285

```

**Comment by windkit** [comment] 2015-08-17 02:23
I have confirmed urge fix works with jclouds, so the code related to range-get could be uncommented

**Comment by yosukehara** [comment] 2015-09-01 12:16
I've closed this issue because you confirmed it was fixed.

**Closed by yosukehara** 2015-09-01 12:16 UTC
