### ISSUE TITLE
[leo_storage] Incomplete Writes are not rolled back

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#561] opened 2016-12-27 07:22 UTC
## Description
Writes cannot obtain enough write quorum are not rolled back and the rejected write will later on propagate to all replicas (through read-repair), which users do not expect.

## Illustration
For a (N=3, W=2), when two replicas fail, the write is rejected with code `500`
Later on when the two replicas return, they would be "fixed" to hold the rejected write, while user expect it is not written.

**Begin**
```
$ ./leofs-adm whereis test/test.txt
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |          node          |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | S4@192.168.100.40      | 5ca400ad12387f6fd23150ba54f2a1b7     |         3K |   63834dbb20 | false          |              0 | 5440fb2c55ce3  | 2016-12-20 13:44:59 +0900
       | S3@192.168.100.39      | 5ca400ad12387f6fd23150ba54f2a1b7     |         3K |   63834dbb20 | false          |              0 | 5440fb2c55ce3  | 2016-12-20 13:44:59 +0900
       | S1@192.168.100.37      | 5ca400ad12387f6fd23150ba54f2a1b7     |         3K |   63834dbb20 | false          |              0 | 5440fb2c55ce3  | 2016-12-20 13:44:59 +0900
```

**Failure of two replicas**
```
$ ./leofs-adm whereis test/test.txt
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |          node          |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | S4@192.168.100.40      | 5ca400ad12387f6fd23150ba54f2a1b7     |         3K |   63834dbb20 | false          |              0 | 5440fb2c55ce3  | 2016-12-20 13:44:59 +0900
       | S3@192.168.100.39      |                                      |            |              |                |                |                |
       | S1@192.168.100.37      |                                      |            |              |                |                |                |
```

**Attempt to Update (Should be rejected) [OK]**
```
$ ./s3cmd put README.md s3://test/test.txt
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'README.md' -> 's3://test/test.txt'  [1 of 1]
 14932 of 14932   100% in    0s     3.22 MB/s  done
WARNING: Upload failed: /test.txt (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 3 sec...
```

**Replicas back**
```
$ ./leofs-adm whereis test/test.txt
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |          node          |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | S4@192.168.100.40      | 5ca400ad12387f6fd23150ba54f2a1b7     |        15K |   52e1144808 | false          |              0 | 54423e7dde244  | 2016-12-21 13:51:19 +0900
       | S3@192.168.100.39      | 5ca400ad12387f6fd23150ba54f2a1b7     |         3K |   63834dbb20 | false          |              0 | 5440fb2c55ce3  | 2016-12-20 13:44:59 +0900
       | S1@192.168.100.37      | 5ca400ad12387f6fd23150ba54f2a1b7     |         3K |   63834dbb20 | false          |              0 | 5440fb2c55ce3  | 2016-12-20 13:44:59 +0900
```

**Read (Return Newest Version) [??]**
```
$ ./s3cmd get s3://test/test.txt dl
download: 's3://test/test.txt' -> 'dl'  [1 of 1]
 14932 of 14932   100% in    0s     3.23 MB/s  done
```

**Replicas got fixed [??]**
```
$ ./leofs-adm whereis test/test.txt
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |          node          |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | S4@192.168.100.40      | 5ca400ad12387f6fd23150ba54f2a1b7     |        15K |   52e1144808 | false          |              0 | 54423e7dde244  | 2016-12-21 13:51:19 +0900
       | S3@192.168.100.39      | 5ca400ad12387f6fd23150ba54f2a1b7     |        15K |   52e1144808 | false          |              0 | 54423e7dde244  | 2016-12-21 13:51:19 +0900
       | S1@192.168.100.37      | 5ca400ad12387f6fd23150ba54f2a1b7     |        15K |   52e1144808 | false          |              0 | 54423e7dde244  | 2016-12-21 13:51:19 +0900
```

**Comment by mocchira** [comment] 2016-12-27 08:07
AFAIK
Almost storage products that adopts eventual consistency have fixed incomplete writes by not rollback but identifying the Error caused by TIMEOUT or not so a client receiving 504 (means TIMEOUT) should take into account the request may be succeeded.

**Comment by mocchira** [comment] 2016-12-27 08:29
Reference:
- http://www.datastax.com/dev/blog/how-cassandra-deals-with-replica-failure
- https://quabase.sei.cmu.edu/mediawiki/index.php/Writes_with_Unavailable_Replicas
  - "no rollback: write returns replication error" is what I suggested the above

**Closed** 2017-05-08 01:51 UTC
Labels: Improve, Priority-MIDDLE, v1.4
